FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

CMD ["sh", "-c", "npx sequelize-cli db:create --config src/utils/database.js || true && npx sequelize-cli db:migrate --config src/utils/database.js --migrations-path src/database/migrations"]

